mysql:
  user: root
  password: Leo123213..
  ip: 127.0.0.1
  port: 3306
  database: star_game
  charset: utf8mb4
  parseTime: True
  loc: Local

boss:
  account: adminmaster
  password: Leo123213..
  uid: 88888888
  nickName: 星盟主

salt:
  client: 1StarGameClient1
  server: 2StarGameServer2

redis:
  Addr: localhost:6379
  Password: ""
  DB: 0
  PoolSize: 100
  MinIdleConns: 100